// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/platform/proxy/dnscache.go

// Package proxy is a generated GoMock package.
package proxy

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDNSCache is a mock of DNSCache interface.
type MockDNSCache struct {
	ctrl     *gomock.Controller
	recorder *MockDNSCacheMockRecorder
}

// MockDNSCacheMockRecorder is the mock recorder for MockDNSCache.
type MockDNSCacheMockRecorder struct {
	mock *MockDNSCache
}

// NewMockDNSCache creates a new mock instance.
func NewMockDNSCache(ctrl *gomock.Controller) *MockDNSCache {
	mock := &MockDNSCache{ctrl: ctrl}
	mock.recorder = &MockDNSCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSCache) EXPECT() *MockDNSCacheMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockDNSCache) Fetch(ctx context.Context, addr string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, addr)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockDNSCacheMockRecorder) Fetch(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockDNSCache)(nil).Fetch), ctx, addr)
}

// LookupIP mocks base method.
func (m *MockDNSCache) LookupIP(ctx context.Context, addr string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIP", ctx, addr)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIP indicates an expected call of LookupIP.
func (mr *MockDNSCacheMockRecorder) LookupIP(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIP", reflect.TypeOf((*MockDNSCache)(nil).LookupIP), ctx, addr)
}

// Refresh mocks base method.
func (m *MockDNSCache) Refresh() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Refresh")
}

// Refresh indicates an expected call of Refresh.
func (mr *MockDNSCacheMockRecorder) Refresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockDNSCache)(nil).Refresh))
}

// Stop mocks base method.
func (m *MockDNSCache) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockDNSCacheMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDNSCache)(nil).Stop))
}
